import express from 'express';
import CondidateController from '../Controllers/condidate.controller';
import bodyParser from 'body-parser';
var jsonParser = bodyParser.json();
const CondidateRouter=express.Router();
CondidateRouter.delete("/DeleteCondidate/:id",CondidateController.DeleteCondidate);
CondidateRouter.post("/AddCondidate",jsonParser, CondidateController.AddCondidate);
CondidateRouter.get("/GetCandidates", CondidateController.GetAll);
CondidateRouter.get("/GetById/:id", CondidateController.GetById);
CondidateRouter.get("/GetByJobId/:id", CondidateController.GetByJobId);
CondidateRouter.put("/UpdateCondidate/:id",jsonParser, CondidateController.UpdateCondidate);
export default CondidateRouter;